### ISSUE TITLE
How to get .pkpass file?

### ISSUE THREAD

**Issue by ZdenekKrcal** [malkovro/add_to_wallet#4]
Hi, please how can I get pkpass file and is it enough to add this file to the app and use it for all devices?

**Comment by workerbee22** [comment]
Hey @ZdenekKrcal I'm working through this also at the moment, because trying to create an **RFID Security Access pass** in Apple Wallet. My investigations so far might help. 

Seeming like here is Apple documentation about Building a Pass. It is an Apple Signed zipped binary file. See here goes through the process to get to a `.pkpass` file:

https://developer.apple.com/documentation/walletpasses/building_a_pass

**Comment by malkovro** [comment]
At Barkibu we work with a Rails backend so we leverage the https://github.com/pgharts/passbook to help us in the generation of the pkpass file.
Following Apple's specification provided in the link above ⬆️
